sourcedir: 'PATH_TO_REPOSITORY'
codedir: 'PATH_TO_REPOSITORY/scripts/python_scripts'
metadatadir: 'PATH_TO_REPOSITORY/metadata'
logdir: 'PATH_TO_REPOSITORY/logs'
sessions: ['L_RS_090817',
           'L_RS_100817',
           'L_RS_250717',
           'L_SNR_090817',
           'L_SNR_100817',
           'L_SNR_250717',
           'L_RF_260617',
           'L_RF_280617',
           'A_RS_140819',
           'A_RS_150819',
           'A_RS_160819',
           'A_SNR_041018',
           'A_SNR_140819',
           'A_SNR_150819',
           'A_SNR_160819',
           'A_RF_280818',
           'A_RF_290818'
           ]
sample_sessions: ['L_RS_090817', 'A_RS_150819']
nsp_count: 8
samplerate: 30000
samplerate_unit: 'Hz'
eyeclosed_threshold: 10
eyesig_unit: 'mV'
SNR_threshold: 2.0
