name: rs_data
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - appdirs=1.4.3=py_1
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2019.11.27=0
  - cairo
  - certifi=2019.11.28=py37_0
  - cffi
  - chardet=3.0.4=py37_1003
  - cryptography
  - cycler=0.10.0=py37_0
  - datrie
  - docutils=0.15.2=py37_0
  - expat
  - fontconfig
  - freetype
  - fribidi
  - gitdb2=2.0.6=py_0
  - gitpython=3.0.5=py_0
  - glib
  - graphite2
  - graphviz
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - icu
  - idna=2.8=py37_1000
  - importlib_metadata=1.3.0=py37_0
  - intel-openmp
  - jpeg
  - jsonschema=3.2.0=py37_0
  - kiwisolver
  - libffi
  - libpng
  - libtiff
  - libxcb
  - libxml2
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools=8.0.2=py_0
  - numpy-base
  - openssl
  - pango
  - pcre
  - pip=19.3.1=py37_0
  - pixman
  - psutil
  - pycparser=2.19=py37_1
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt
  - pyrsistent
  - pysocks=1.7.1=py37_0
  - python
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml
  - qt
  - ratelimiter=1.2.0=py37_1000
  - requests=2.22.0=py37_1
  - setuptools=42.0.2=py37_0
  - sip
  - six=1.13.0=py37_0
  - smmap2=2.0.5=py_0
  - snakemake-minimal=5.8.1=py_0
  - sqlite
  - tk
  - tornado
  - urllib3=1.25.7=py37_0
  - wheel=0.33.6=py37_0
  - wrapt
  - xz
  - yaml
  - zipp=0.6.0=py_0
  - zlib
  - zstd
  - pip:
    - matplotlib==3.4.3
    - docopt==0.6.2
    - elephant==0.10.0
    - future==0.18.2
    - h5py==2.10.0
    - isodate==0.6.0
    - lxml==4.4.2
    - neo==0.9.0
    - nixio==1.5.0
    - numpy==1.17.4
    - odml==1.4.5
    - odmltables==1.0.0
    - pandas==1.0.1
    - pathlib==1.0.1
    - quantities==0.12.3
    - rdflib==4.2.2
    - scipy==1.4.1
    - tqdm==4.42.1
    - xlrd==1.2.0
    - xlwt==1.3.0
    - joblib
    - seaborn